version: '3'

services:
  hotel:
    container_name: hotel
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code

  contacts:
    container_name: contacts
    build: ./contacts
    ports:
      - "5000:5000"
